#ifndef LISTGROUPWIDGET_H
#define LISTGROUPWIDGET_H

#include <QWidget>
#include <QObject>
#include <QWidget>
#include <QLabel>
#include <QLayout>

#include "icondata.h"
#include "commtype.h"

/*!
 * \brief The ListGroupWidget class is used to display a pre-saved group of
 *        devices and their settings in a single list widget. It displays the name
 *        of the group, up to 5 device previews as IconData, and the connection state
 *        of the associated devices.
 */
class ListGroupWidget : public QWidget
{
    Q_OBJECT

public:
    /*!
     * \brief ListGroupWidget constructor
     */
    explicit ListGroupWidget(QWidget *parent = 0);

    /*!
     * \brief setup create a ListGroupWidget
     * \param name name of group
     * \param devices devices in group
     * \param colors Color groups for devices using multi color routines.
     * \param statePixmap connection state of the devices.
     * \param width width connectionList showing this group.
     * \param height desired height of this ListGroupWidget.
     */
    void setup(const QString& name,
               const std::list<SLightDevice>& devices,
               const std::vector<std::vector<QColor> >& colors,
               QPixmap statePixmap,
               int width,
               int height);

private:

    /*!
     * \brief mName namme of group
     */
    QLabel *mName;

    /*!
     * \brief mStatusIcon connection status of all the devices in the group.
     */
    QLabel *mStatusIcon;

    /*!
     * \brief mPreviews preview of a device in the group. Uses an icon generated by
     *        the icon data.
     */
    std::vector<QLabel*>  mPreviews;

    /*!
     * \brief mIconData data for the previews of the devices in groups.
     */
    std::vector<IconData> mIconData;

    /*!
     * \brief mLayout layout for widget
     */
    QHBoxLayout *mLayout;
};

#endif // LISTGROUPWIDGET_H
